[package]
name = "p910nd-rust"
version = "0.1.0"
authors = ["Ken Yap"]
license = "GPL3"
repository = "https://github.com/kenyapcomau/p910nd-rust"

[dependencies]
lockfile = "0.4.0"
clap = "4.4.18"
log = "0.4.20"
stderrlog = "0.5.4"
syslog = "6.1.0"
daemonize = "0.5.0"

[lib]
name = "p910nd"
